import { ListaUsuariosInterface } from "./usuarios";

export interface ListaEvaluacionesInterface
{
    id_Evaluacion: number;
    usuario_id: number;
    colaborador_id: number;
    calificacionFinal?: number;
    estado?: string;
    clfc_Pregunta1?: number | null;
    clfc_Pregunta2?: number | null;
    clfc_Pregunta3?: number | null;
    clfc_Pregunta4?: number | null;
    clfc_Pregunta5?: number | null;
    clfc_Pregunta6?: number | null;
    clfc_Pregunta7?: number | null;
    clfc_Pregunta8?: number | null;
    clfc_Pregunta9?: number | null;
    clfc_Pregunta10?: number | null;
    clfc_Pregunta11?: number | null;
    clfc_Pregunta12?: number | null;
    clfc_Pregunta13?: number | null;
    clfc_Pregunta14?: number | null;
    clfc_Pregunta15?: number | null;
    clfc_Pregunta16?: number | null;
    clfc_Pregunta17?: number | null;
    clfc_Pregunta18?: number | null;
    clfc_Pregunta19?: number | null;
    clfc_Pregunta20?: number | null;
    clfc_Pregunta21?: number | null;
    clfc_Pregunta22?: number | null;
    clfc_Pregunta23?: number | null;
    clfc_Pregunta24?: number | null;
    clfc_Pregunta25?: number | null;
    clfc_Pregunta26?: number | null;
    clfc_Pregunta27?: number | null;
    clfc_Pregunta28?: number | null;
    clfc_Pregunta29?: number | null;
    clfc_Pregunta30?: number | null;
    clfc_Pregunta31?: number | null;
    clfc_Pregunta32?: number | null;
    clfc_Pregunta33?: number | null;
    clfc_Pregunta34?: number | null;
    clfc_Pregunta35?: number | null;
    clfc_Pregunta36?: number | null;
    clfc_Pregunta37?: number | null;
    clfc_Pregunta38?: number | null;
    clfc_Pregunta39?: number | null;
    clfc_Pregunta40?: number | null;
    clfc_Pregunta41?: number | null;
    clfc_Pregunta42?: number | null;
    clfc_Pregunta43?: number | null;
    clfc_Pregunta44?: number | null;
    clfc_Pregunta45?: number | null;
    clfc_Pregunta46?: number | null;
    clfc_Pregunta47?: number | null;
    clfc_Pregunta48?: number | null;
    clfc_Pregunta49?: number | null;
    clfc_Pregunta50?: number | null;
    clfc_Pregunta51?: number | null;
    clfc_Pregunta52?: number | null;
    usuariosModel: ListaUsuariosInterface;

}