export interface ListaObservacionesInterface
{
    id_Observacion: number;
    evaluacion_id: number;
    observacion1?: string;
    observacion2?: string;
    observacion3?: string;
    observacion4?: string;
    observacion5?: string;
    observacion6?: string;
    observacion7?: string;
    observacion8?: string;
    observacion9?: string;
    observacion10?: string;
    observacion11?: string;
    observacion12?: string;
    observacion13?: string;
    observacion14?: string;
    observacion15?: string;
    observacion16?: string;
    observacion17?: string;
    observacion18?: string;
    observacion19?: string;
    observacion20?: string;
    observacion21?: string;
    observacion22?: string;
    observacion23?: string;
    observacion24?: string;
    observacion25?: string;
    observacion26?: string;
    observacion27?: string;
    observacion28?: string;
    observacion29?: string;
    observacion30?: string;
    observacion31?: string;
    observacion32?: string;
    observacion33?: string;
    observacion34?: string;
    observacion35?: string;
    observacion36?: string;
    observacion37?: string;
    observacion38?: string;
    observacion39?: string;
    observacion40?: string;
    observacion41?: string;
    observacion42?: string;
    observacion43?: string;
    observacion44?: string;
    observacion45?: string;
    observacion46?: string;
    observacion47?: string;
    observacion48?: string;
    observacion49?: string;
    observacion50?: string;
    observacion51?: string;
    observacion52?: string;


}